name: CI
on:
  pull_request: {}
  push:
    branches:
       - staging
       - trying
jobs:
  tests:
    runs-on: ubuntu-latest
    env: 
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: 'true'
      - name: Restore cache
        uses:  actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: "Compile tests"
        uses: actions-rs/cargo@v1
        with:
           command: test
           args: --no-run
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: 'true'
          components: clippy
      - name: "Run clippy"
        uses: actions-rs/cargo@v1
        with:
            command: clippy
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            override: 'true'
            components: rustfmt
      - name: "Check formatting"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check